#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm run build:prod
echo "Lint TS"
npm run lint:ts

echo "Lint Styles"
npm run lint:scss

# echo "Npm Testing UNIT"
# npm run test:unit

echo "build storybook"
npm run storybook:build

echo "Npm Testing ui"
npm run test:ui
