#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# echo "Lint TS"
# npm run lint:ts
npx lint-staged

# echo "Lint Styles"
# npm run lint:scss

# echo "Npm Testing UNIT"
# npm run test:unit

# echo "build storybook"
# npm run storybook:build

# echo "Npm Testing ui"
# npm run test:ui

# echo "Build product"
# npm run build:prod